x-default-agents: &default-agents
  agents:
    queue: "${AGENT_QUEUE:-packages}"

steps:
  - key: build-solana-packages
    label: ":hammer_and_wrench: solana-packages"
    <<: *default-agents

    command: |
      source .buildkite/lib.bash

      [[ -v REMOTE ]] || log::fatal "Must specify REMOTE"
      [[ -v TAG ]] || log::fatal "Must specify TAG"

      git::repos::add git@github.com:abklabs/svmkit
      git::repos::add https://github.com/solana-labs/solana
      git::repos::summary
      git::repos::clone

      # add the repos to git/config
      cat .buildkite/solana-packages/git.config >> solana/.git/config

      bk::group "Building packages for $$REMOTE $$TAG"
      ( cd solana && ../svmkit/build/solana-build  "$$REMOTE" "$$TAG" )

    artifact_paths:
      - build/*.deb

  - label: "Testing $BUILDKITE_BUILD_URL"
    depends_on: build-solana-packages
    trigger: solana-lab
    async: false
    build:
      branch: "${SVMKIT_BUILDKITE_BRANCH:-${BUILDKITE_BRANCH}}"
      env:
        SVMKIT_BRANCH: ${SVMKIT_BRANCH:-}
        PULUMI_SVMKIT_BRANCH: ${PULUMI_SVMKIT_BRANCH:-}
        TOOLING_BRANCH: ${TOOLING_BRANCH:-}
        SOLANA_LAB_BRANCH: ${SOLANA_LAB_BRANCH:-}
        PARENT_BUILD_ID: "${BUILDKITE_BUILD_ID}"
        ARTIFACT_PATTERN: "build/*"
