x-default-agents: &default-agents
  agents:
    queue: "${AGENT_QUEUE:-default}"

env:
  AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION:-us-west-2}"
  GOOGLE_PROJECT: "${GOOGLE_PROJECT:-svmkit}"
  PULUMI_STACK_NAME: "abklabs/buildkite-solana-lab-${BUILDKITE_BUILD_NUMBER}"

steps:
  - key: build
    label: ":hammer_and_wrench: Build svmkit and pulumi-svmkit"
    if: build.env("SVMKIT_BRANCH") != null || build.env("PULUMI_SVMKIT_BRANCH") != null
    <<: *default-agents

    command: |
      source .buildkite/lib.bash

      if [[ -v SVMKIT_BRANCH ]] ; then
          git::repos::add git@github.com:abklabs/svmkit.git svmkit
      fi

      git::repos::add git@github.com:abklabs/pulumi-svmkit.git pulumi-svmkit 
      git::repos::summary
      git::repos::clone

      if [[ -v SVMKIT_BRANCH ]] ; then
          bk::group "Building svmkit"
          ( cd svmkit && make)
      fi

      bk::group "Building pulumi-svmkit"
      (
          cd pulumi-svmkit
          if [[ -v SVMKIT_BRANCH ]] ; then
              log::info "Patching pulumi-svmkit to use local svmkit"
              ( cd provider && go mod edit -replace github.com/abklabs/svmkit/pkg=../../svmkit/pkg )
          fi
          make
      )
      tar -zcf pulumi-artifacts.tgz pulumi-svmkit/sdk pulumi-svmkit/bin

    artifact_paths:
      - pulumi-artifacts.tgz

  - key: solana-lab
    label: ":test_tube: solana-lab"
    <<: *default-agents
    depends_on: ["build"]
    concurrency: 1
    concurrency_group: pulumi-testing

    command: |
      source .buildkite/lib.bash

      git::repos::add git@github.com:abklabs/solana-lab.git solana-lab
      git::repos::add git@github.com:abklabs/tooling.git tooling

      # Build kite section describing branches
      git::repos::summary

      # Get to work
      git::repos::clone

      USE_PIPELINE_PULUMI_SVMKIT=false

      bk::group "Searching for pipeline build of pulumi-svmkit"
      if buildkite-agent artifact search pulumi-artifacts.tgz ; then
        log::info "Downloading Pulumi SDK and provider plugin artifacts"
        buildkite-agent artifact download pulumi-artifacts.tgz .
        tar zxf pulumi-artifacts.tgz
        USE_PIPELINE_PULUMI_SVMKIT=true
      fi

      setup-aws-credentials
      setup-gcp-credentials

      # Now that we are here, go to solana-lab:
      # 1) Install pulumi
      # 2) Create a stack
      # 4) run tests

      # Add with-*pulumi* scripts to the path
      PATH=$$(realpath ./tooling/bin):$$PATH
      (
        cd solana-lab
        bk::group "Setting up for Test Suite"
        pulumi stack init "$$PULUMI_STACK_NAME"
        pulumi stack select "$$PULUMI_STACK_NAME"

        PREFIX=()

        if $$USE_PIPELINE_PULUMI_SVMKIT ; then
           log::info "Using a pipeline build of pulumi-svmkit"
           PREFIX+=(with-local-pulumi-svmkit ../pulumi-svmkit)
        else
           log::info "Using the released pulumi-svmkit"
           pulumi install
        fi

        # with-local-pulumi-svmkit handles pulumi install
        "$${PREFIX[@]}" with-pulumi-up with-rpc-forwarded prove --ext .ts --ext .t test

        pulumi stack rm --yes
      )

  - key: cleanup
    label: ":broom: Cleanup wayward stacks"
    <<: *default-agents
    command: |
      source .buildkite/lib.bash

      git::repos::add git@github.com:abklabs/solana-lab.git solana-lab
      git::repos::summary
      git::repos::clone

      USE_PIPELINE_PULUMI_SVMKIT=false

      bk::group "Searching for pipeline build of pulumi-svmkit"
      if buildkite-agent artifact search pulumi-artifacts.tgz ; then
        echo "-- Downloading Pulumi SDK and provider plugin artifacts"
        buildkite-agent artifact download pulumi-artifacts.tgz .
        tar zxf pulumi-artifacts.tgz
        USE_PIPELINE_PULUMI_SVMKIT=true
      fi

      setup-aws-credentials
      setup-gcp-credentials
      (
        cd solana-lab
        if pulumi stack select "$$PULUMI_STACK_NAME" 2>/dev/null; then
          bk::group ":warning: Stack '$$PULUMI_STACK_NAME' exists. Destroying..."
          pulumi install
          pulumi destroy --yes || echo "❌ Failed to destroy stack $$PULUMI_STACK_NAME"
          if pulumi stack rm --yes; then
             bk::group ":white_check_mark: Stack '$$PULUMI_STACK_NAME' cleanup complete."
          else
             bk::group ":x: Failed to destroy stack $$PULUMI_STACK_NAME"
             exit 1
          fi
        else
          bk::group ":white_check_mark: Stack '$$PULUMI_STACK_NAME' does not exist. Nothing to destroy."
        fi
      )

    depends_on: ["solana-lab"]
    allow_dependency_failure: true
